Repository noelmace/monocli, pull requests merged in 2020-04, with the labels that each got.

#2 fix(add): include scopes with # or / when rewriting
  src/commands/add.ts
  tap-snapshots/test-tap-commands-add.ts-TAP.test.js
  test/tap/commands/add.ts
Labels: bug

#6 fix(add): uncommited files
  src/commands/add.ts
  test/tap/commands/add.ts
Labels: bug

#18 ci: test
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/models/git.ts
  tap-snapshots/test-tap-commands-help.ts-TAP.test.js
Labels: dev

#19 (add) use subtree
  src/commands/add.ts
  src/models/main-command.ts
  tap-snapshots/test-tap-commands-add.ts-TAP.test.js
  tap-snapshots/test-tap-commands-help.ts-TAP.test.js
  tap-snapshots/test-tap-commands-spull.ts-TAP.test.js
  test/common.ts
  test/tap/commands/add.ts
Labels: bug, enhancement

#8 Generate .gitignore file using gitignore.io
  .gitignore
Labels: dev

#22 ci: check style on push and PR
  .github/workflows/style.yml
Labels: dev

#23 (update) resolve conflicts
  .eslintrc.js
  .github/workflows/test.yml
  bin/monocli
  package.json
  src/cli.ts
  src/commands/add.ts
  src/commands/check.ts
  src/commands/help.ts
  src/commands/mv.ts
  src/commands/spull.ts
  src/commands/spush.ts
  src/commands/update.ts
  src/models/command.ts
  src/models/errors.ts
  src/models/git.ts
  src/models/main-command.ts
  src/models/monorepo-command.ts
  src/utils/build-command.ts
  src/utils/command.ts
  src/utils/minimist.ts
  src/utils/prompt.ts
  tap-snapshots/test-tap-commands-help.ts-TAP.test.js
  tap-snapshots/test-tap-commands-mv.ts-TAP.test.js
  tap-snapshots/test-tap-commands-spush.ts-TAP.test.js
  tap-snapshots/test-tap-commands-update.ts-TAP.test.js
  test/.eslintrc
  test/common.ts
  test/tap/commands/add.ts
  test/tap/commands/check.ts
  test/tap/commands/help.ts
  test/tap/commands/mv.ts
  test/tap/commands/spull.ts
  test/tap/commands/spush.ts
  test/tap/commands/status.ts
  test/tap/commands/update.ts
  test/tap/models/git.ts
  test/tap/utils/fs.ts
  test/tap/utils/log.ts
  test/tap/utils/parse.ts
  test/tap/utils/path.ts
Labels: enhancement

#24 (spush) save branch before force push
  src/commands/spull.ts
  src/commands/spush.ts
  tap-snapshots/test-tap-commands-spush.ts-TAP.test.js
  test/tap/commands/spush.ts
Labels: enhancement
